services:
  mongodb:
    image: mongo:8.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongodb_data:/data/db

  node-app:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
      HOST: 0.0.0.0
    ports:
      - "6000:3000"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
