const PROVIDERTYPES = {
    TOURSANDTRAVELS: 1,
    HOTELS: 2,
    VEHICLERENTALS: 3,
    RESTOURENTS: 4
}

const CONTACTUSTYPES = {
    ADDRESS: 1,
    EMAIL: 2,
    PHONE: 3
}

const PRIVACYANDPOLICYTYPES = {
    USERPOLICY: 1,
    PROVIDERPOLICY: 2,
    BOKKINGPOLICYFORUSER: 3,
    BOKKINGPOLICYFORPROVIDER: 3,
    //IF ANY OTHER
}

const PLACETYPES = {
    FOREST: 1,
    ADVENTURE: 2,
    COSTAL: 3, // BEACHES
    TRECKING: 4,
    DEVOTINAL: 5,
    TECHNOLOGICAL: 6,
    NATURE: 7,
    MOUTAINS: 8
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const EVENTANDCONCERTYPES = {
    SINGINGCONCERT: 1,
    EXHIBITION: 2,
    SPORTSEVENT: 3,
    MOVIEEVENT: 4,
    DEVOTINALEVENT: 5,
    TECHNOLOGICALEVENT: 6,
    OTHERS: 7,
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const OTPTYPES = {
    USER: 1,
    TOURSANDTRAVELS: 2,
    HOTELS: 3,
    VEHICLERENTALS: 4,
    RESTOURENTS: 5
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const NOTIFICATIONRECIEVERTYPES = {
    FORUSER: 1,
    FORTOURSANDTRAVELS: 2,
    FORHOTELS: 3,
    FORVEHICLERENTALS: 4,
    FORRESTOURENTS: 5
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const MESSAGESENTTYPES = {
    USER_SENT: 1,
    TOURSANDTRAVELS_SENT: 2,
    HOTELS_SENT: 3,
    VEHICLERENTALS_SENT: 4,
    RESTOURENTS_SENT: 5
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const MESSAGETYPES = {
    MESSAGE: 1,
    IMAGE: 2,
    VIDEO: 3,
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const VIDEOMODULETYPE = {
    TOURSANDTRAVELS: 1,
    HOTELS: 2,
    VEHICLERENTALS: 3,
    RESTOURENTS: 4,
    USER: 5
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const VIDEOTYPE = {
    VIDEO: 1,
    GIF: 2,
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const SUBSCRIPTIONTYPE = {
    MONTH_1: 1,
    MONTH_3: 2,
    MONTH_6: 3,
    MONTH_12: 4,
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const SUBSCRIPTIONSTATUS = {
    SUCCESS: 1,
    FAILED: 2,
    PROCESS: 3,
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

const ROOMTYPE = {
    SINGLEBEDROOM: 1,
    DOUBLEBEDROOM: 2,
    THRIBLEBEDROOM: 3,
    //IF ANY OTHER AND PROVIDE VALID TYPES THIS ARE EXAMPLES
}

module.exports =  {
    PROVIDERTYPES,
    CONTACTUSTYPES,
    PRIVACYANDPOLICYTYPES,
    PLACETYPES,
    EVENTANDCONCERTYPES,
    OTPTYPES,
    NOTIFICATIONRECIEVERTYPES,
    MESSAGESENTTYPES,
    MESSAGETYPES,
    VIDEOMODULETYPE,
    VIDEOTYPE,
    SUBSCRIPTIONTYPE,
    SUBSCRIPTIONSTATUS,
    ROOMTYPE,
}